# Travis CI configuration file for running tests
language: python

branches:
  only:
    - master

python:
  - "2.7"

services:
  - docker
  
addons:
  apt:
    packages:
      - nodejs
      - python-demjson

before_install:
  - sudo apt-get update
  - sudo apt-get install docker-engine

install:
  - "pip install --allow-all-external -r requirements.txt"
  - "pip install --allow-all-external demjson"

env:
  - MAKE_TARGET=docker.test.shard SHARD=0 SHARDS=3
  - MAKE_TARGET=docker.test.shard SHARD=1 SHARDS=3
  - MAKE_TARGET=docker.test.shard SHARD=2 SHARDS=3
  - MAKE_TARGET=test.syntax
  - MAKE_TARGET=test.edx_east_roles

script:
  - cd playbooks
  - comm -12 <(git diff --name-only ${TRAVIS_COMMIT_RANGE} | sort) <(python ../util/ansible-deps.py --playbook ../docker/plays/edxapp.yml --output-role-files | sort)
  - cd ..
  - docker --version
  - make --version
  - travis_wait 40 make --keep-going $MAKE_TARGET SHARD=$SHARD SHARDS=$SHARDS
